DATABASE_HOST = 'localhost'
DATABASE_USER = 'postgres'
DATABASE_PASS = 'root'
DATABASE_NAME = 'radar'

COLLECTOR_ADDRESS = '/dev/ttyACM0'

DEFAULT_LOG_DIR = "log/"
DEFAULT_FILE_NAME_SERVER_REPORT = DEFAULT_LOG_DIR + "report.log"