DATABASE_HOST = 'localhost'
DATABASE_USER = 'postgres'
DATABASE_PASS = 'root'
DATABASE_NAME = 'radar'

LATITUDE 	= 0
LONGITUDE 	= 0

COLLECTOR_ADDRESS = '/dev/ttyACM0'

DEFAULT_LOG_DIR = "log"
DEFAULT_FILE_NAME_SERVER_REPORT = "report.log"