Listen 80
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

<VirtualHost *:80>
    ProxyPass / http://server:8000/
    ProxyPassReverse / http://server:8000/
    Header always set X-Proxied-By "Apache"
</VirtualHost>
