global:
  scrape_interval: 5s
  evaluation_interval: 15s

alerting:
  alertmanagers:

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['server:8000']
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):\\d+"
        target_label: instance

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
    metric_relabel_configs:
      - source_labels: [ 'container_label_com_docker_swarm_service_name' ]
        target_label: 'service'
      - source_labels: [ 'name' ]
        target_label: 'container'