echo "***************************************
* Instalando requerimentos do projeto django
***************************************";

source venvs/django/bin/activate ; 

pip install Django==1.9.4 ; 
# pip install Landscape-Client ; 
pip install Markdown==2.6.6 ; 
# pip install PAM==0.4.2 ; 
pip install Pillow==2.3.0 ; 
# pip install Twisted-Core==13.2.0 ; 
# pip install apt-xapian-index==0.45 ; 
# pip install argparse==1.2.1 ; 
# pip install backports-abc==0.4 ; 
# pip install backports.ssl-match-hostname==3.5.0.1 ; 
# pip install certifi==2016.2.28 ; 
# pip install chardet==2.0.1 ; 
# pip install colorama==0.2.5 ; 
# pip install configobj==4.7.2 ; 
# pip install decorator==3.4.0 ; 
# pip install django-appconf==1.0.1 ; 
pip install django-cleanup==0.4.2 ; 
pip install django-crispy-forms==1.6.0 ; 
pip install django-filter==0.13.0 ; 
pip install django-imagekit==3.3 ; 
pip install django-rest==0.0.1 ; 
pip install djangorestframework==3.3.3 ; 
pip install djangorestframework-jsonp==1.0.2 ; 
# pip install html5lib==0.999 ; 
# pip install matplotlib==1.3.1 ; 
# pip install mechanize==0.2.5 ; 
# pip install nose==1.3.7 ; 
# pip install numpy==1.8.2 ; 
pip install pilkit==1.1.13 ; 
pip install psycopg2==2.4.5 ; 
# pip install pyOpenSSL==0.13 ; 
# pip install pygobject==3.12.0 ; 
# pip install pygraphviz==1.2 ; 
# pip install pyparsing==2.0.1 ; 
# pip install pyserial==2.6 ; 
# pip install python-Levenshtein==0.11.2 ; 
# pip install python-apt==0.9.3.5ubuntu2 ; 
# pip install python-dateutil==1.5 ; 
# pip install python-debian==0.1.21-nmu2ubuntu2 ; 
# pip install pytidylib==0.2.4 ; 
# pip install pytz==2012c ; 
# pip install pyxdg==0.25 ; 
# pip install requests==2.2.1 ; 
# pip install scipy==0.13.3 ; 
# pip install singledispatch==3.4.0.3 ; 
# pip install six==1.5.2 ; 
# pip install ssh-import-id==3.21 ; 
# pip install tornado==4.3 ; 
# pip install uTidylib==0.2 ; 
# pip install urllib3==1.7.1 ; 
# pip install virtualenv==1.11.4 ; 
# pip install wheel==0.24.0 ; 
# pip install wsgiref==0.1.2 ; 
# pip install zope.interface==4.0.5
