# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-05 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=1000)),
                ('subtitle', models.CharField(blank=True, default='', max_length=1000)),
                ('info', models.TextField(blank=True, default='')),
                ('index', models.IntegerField(default=0)),
                ('externURL', models.URLField(blank=True, default='', verbose_name='Extern link')),
                ('image', models.ImageField(null=True, upload_to='about_images')),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('icao', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AirplaneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(blank=True, default='', max_length=100)),
                ('airline', models.CharField(blank=True, default='', max_length=100)),
                ('airlineCountry', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('altitude', models.IntegerField(default=0)),
                ('verticalVelocity', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('horizontalVelocity', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('groundTrackHeading', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('airplane', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='radarlivre_api.Airplane')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('prefix', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('timestampData', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('calsign', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('airline', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('airlineCountry', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('airplane', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='radarlivre_api.Airplane')),
                ('destine', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights_coming', to='radarlivre_api.Airport')),
                ('origin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights_leaving', to='radarlivre_api.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=1000)),
                ('subtitle', models.CharField(blank=True, default='', max_length=1000)),
                ('info', models.TextField(blank=True, default='')),
                ('showDate', models.DateTimeField()),
                ('vibrate', models.BooleanField(default=True)),
                ('song', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('altitude', models.IntegerField(default=0)),
                ('verticalVelocity', models.IntegerField(default=0)),
                ('horizontalVelocity', models.IntegerField(default=0)),
                ('angle', models.IntegerField(default=0)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('timestampSent', models.BigIntegerField(default=0)),
                ('messageDataId', models.CharField(blank=True, default='', max_length=100)),
                ('messageDataPositionEven', models.CharField(blank=True, default='', max_length=100)),
                ('messageDataPositionOdd', models.CharField(blank=True, default='', max_length=100)),
                ('messageDataVelocity', models.CharField(blank=True, default='', max_length=100)),
                ('airplane', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='radarlivre_api.Airplane')),
                ('collector', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='radarlivre_api.Collector')),
                ('flight', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='radarlivre_api.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=1000)),
                ('versionName', models.CharField(blank=True, default='', max_length=1000)),
                ('versionCode', models.IntegerField(default=0)),
                ('lastUpdate', models.DateField(default=0)),
                ('executable', models.FileField(upload_to='softwares/collector')),
            ],
        ),
    ]
