# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=1000)),
                ('subtitle', models.CharField(blank=True, default='', max_length=1000)),
                ('info', models.TextField(blank=True, default='')),
                ('index', models.IntegerField(default=0)),
                ('externURL', models.URLField(blank=True, default='', verbose_name='Extern link')),
                ('image', models.ImageField(null=True, upload_to='about_images')),
            ],
        ),
        migrations.CreateModel(
            name='ADSBMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('icao', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AirplaneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(blank=True, default='', max_length=100)),
                ('airline', models.CharField(blank=True, default='', max_length=100)),
                ('airlineCountry', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('altitude', models.IntegerField(default=0)),
                ('verticalVelocity', models.IntegerField(default=0)),
                ('horizontalVelocity', models.IntegerField(default=0)),
                ('angle', models.IntegerField(default=0)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('airplane', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='radarlivre_api.Airplane')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('prefix', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('altitude', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contrib',
            fields=[
                ('ip', models.CharField(blank=True, max_length=15, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('timestamp', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('calsign', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('airplane', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='route_airplane', to='radarlivre_api.Airplane')),
                ('destine', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destine', to='radarlivre_api.Airport')),
                ('origin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='radarlivre_api.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='HalfObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane', models.CharField(blank=True, default='', max_length=100)),
                ('flight', models.CharField(blank=True, default='', max_length=100)),
                ('latitudeCollector', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('longitudeCollector', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('latitudeEven', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('longitudeEven', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('latitudeOdd', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('longitudeOdd', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('altitude', models.IntegerField(default=0)),
                ('verticalVelocity', models.IntegerField(default=0)),
                ('horizontalVelocity', models.IntegerField(default=0)),
                ('angle', models.IntegerField(default=0)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('timestampSent', models.BigIntegerField(default=0)),
                ('messageDataId', models.CharField(blank=True, default='', max_length=100)),
                ('messageDataPositionEven', models.CharField(blank=True, default='', max_length=100)),
                ('messageDataPositionOdd', models.CharField(blank=True, default='', max_length=100)),
                ('messageDataVelocity', models.CharField(blank=True, default='', max_length=100)),
                ('lastReceived', models.CharField(blank=True, default='', max_length=1)),
                ('evenReceived', models.BooleanField(default=False)),
                ('oddReceived', models.BooleanField(default=False)),
                ('velocityReceived', models.BooleanField(default=False)),
                ('identityReceived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=1000)),
                ('subtitle', models.CharField(blank=True, default='', max_length=1000)),
                ('info', models.TextField(blank=True, default='')),
                ('showDate', models.DateTimeField()),
                ('vibrate', models.BooleanField(default=True)),
                ('song', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('altitude', models.IntegerField(default=0)),
                ('verticalVelocity', models.IntegerField(default=0)),
                ('horizontalVelocity', models.IntegerField(default=0)),
                ('angle', models.IntegerField(default=0)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('airplane', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation_airplane', to='radarlivre_api.Airplane')),
                ('flight', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation_route', to='radarlivre_api.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=1000)),
                ('versionName', models.CharField(blank=True, default='', max_length=1000)),
                ('versionCode', models.IntegerField(default=0)),
                ('lastUpdate', models.DateField(default=0)),
                ('executable', models.FileField(upload_to='softwares/collector')),
            ],
        ),
    ]
