# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radarlivre_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='about',
            name='info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
