# Generated by Django 4.2.1 on 2025-02-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radarlivre_api', '0002_insert_airports_and_airlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='timestamp',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
