# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radarlivre_api', '0002_auto_20160310_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='externURL',
            field=models.URLField(blank=True, default='', verbose_name='Extern link'),
        ),
    ]
