# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radarlivre_api', '0003_about_externurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, default='0.0.0.0', max_length=15)),
                ('latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
            ],
        ),
    ]
