# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radarlivre_api', '0004_contrib'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrib',
            name='timestamp',
            field=models.BigIntegerField(default=0),
        ),
    ]
