# Generated by Django 4.2.1 on 2025-02-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radarlivre_api', '0004_adsbinfo_point_airport_point_collector_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsbinfo',
            name='collectorKey',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
