# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radarlivre_api', '0005_contrib_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrib',
            name='id',
        ),
        migrations.AlterField(
            model_name='contrib',
            name='ip',
            field=models.CharField(blank=True, max_length=15, primary_key=True, serialize=False),
        ),
    ]
