{
 "title": "Radar Livre",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(django_http_requests_total_by_transport_total{instance=\"server\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Processing Time",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket{instance=\"server\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{instance=\"server\"}[$__rate_interval])) by (le))",
     "legendFormat": "50 quantile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{instance=\"server\"}[$__rate_interval])) by (le))",
     "legendFormat": "90 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{instance=\"server\"}[$__rate_interval])) by (le))",
     "legendFormat": "95 quantile"
    }
   ]
  },
  {
   "title": "Database response time",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(django_db_query_duration_seconds_bucket{instance=\"server\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{instance=~\".*\",job=~\".*\",image!=\"\", service=~\".*\", container=~\"(cadvisor|grafana|postgres|prometheus|radar_livre)\"}[$__rate_interval]) ) * 100 ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_fs_reads_bytes_total{instance=~\".*\",job=~\".*\",image!=\"\", service=~\".*\", container=~\"(cadvisor|grafana|postgres|prometheus|radar_livre)\"}[$__rate_interval]))",
     "legendFormat": "read {{container}}"
    },
    {
     "expr": "-(sum by (container) (rate(container_fs_writes_bytes_total{instance=~\".*\",job=~\".*\",image!=\"\", service=~\".*\", container=~\"(cadvisor|grafana|postgres|prometheus|radar_livre)\"}[$__rate_interval])))",
     "legendFormat": "write {{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container) (container_memory_usage_bytes{instance=~\".*\",job=~\".*\",image!=\"\", service=~\".*\", container=~\"(cadvisor|grafana|postgres|prometheus|radar_livre)\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}