var airLines =[
	["AD", "AZU", "Azul Linhas Aereas" ,"Brazil"],
	["G3", "GLO", "GOL Transportes Aereos" ,"Brazil"],
	["??", "GOL", "GOL Transportes Aereos" ,"Brazil"],
	["JJ", "TAM", "TAM Linhas Aereas" ,"Brazil"],
	["M3", "TUS", "ABSA Aerolinhas" ,"Brazil"],
	["O6", "ONE", "Avianca Brazil" ,"Brazil"],
	["P3", "PTB", "Passaredo Transportes Aereos" ,"Brazil"],
	["P8", "PTN", "Pantanal Linhas Aereas" ,"Brazil"],
	["R9", "TSD", "TAF Linhas Aereas" ,"Brazil"],
	["RL", "RIO", "Rio Linhas Aereas" ,"Brazil"],
	["T4", "TIB", "TRIP Linhas Aereas" ,"Brazil"],
	["WH", "WEB", "Webjet Linhas Aéreas" ,"Brazil"],
	["AF", "AFR", "Air France" ,"France"],
	["TP", "TAP", "TAP Portugal" ,"Portugal"],
	["LH", "DLH", "Lufthansa" ,"Germany"],
	["BA", "BAW", "British Airways" ,"United Kingdom"],
	["0B", "JOR", "Blue Air  Blue Transport" ,"Romania"],
	["0J", "JCS", "Jetclub Jetclub" ,"Switzerland"],
	["2C", "TGV", "SNCF" ,"France"],
	["2A", "DBB", "Deutsche Bahn", "Germany"],
	["2R", "VRR", "VIA Rail Canada", "Canada"],
	["0V", "VFC", "VASCO Vietnam Air Service Company", "Vietnam"], 
    ["1B", "BGH", "BH Air", "Bulgaria"], 
    ["1I", "AMB", "Deutsche Rettungsflugwacht", "Germany"], 
    ["1I", "EJA", "Netjets", "USA"], 
    ["1I", "NVR", "Novair/Nova Airlines", "Sweden"], 
    ["1T", "BUC", "Bulgarian Air Charter", "Bulgaria"], 
    ["2D", "OST", "Alania Airlines", "Russia"], 
    ["2E", "PHW", "AVE.com", "United Arab Emirates"], 
    ["2F", "FTA", "Frontier Alaska/Frontier Flying Service", "USA"], 
    ["2F", "IRP", "Payam/IPTAS", "Iran"], 
    ["2I", "SRU", "Star Peru", "Peru"], 
    ["2J", "VBW", "Air Burkina", "Burkina Faso"], 
    ["2K", "GLG", "Aerogal Aerolineas Galapagos", "Ecuador"], 
    ["2L", "OAW", "Helvetic Airways", "Switzerland"], 
    ["2M", "MDV", "Moldavian Airlines", "Moldova"], 
    ["2N", "NTJ", "Nextjet", "Sweden"], 
    ["2N", "UMK", "Yuzmashavia", "Ukraine"], 
    ["2P", "GAP", "Air Philippines", "Philippines"], 
    ["2Q", "SNC", "Air Cargo Carriers", "USA"], 
    ["2S", "SDY", "Island Express", "USA"], 
    ["2T", "ANH", "Alajnihah Airways", "Libya"], 
    ["2W", "WLC", "Welcome Air", "Austria"], 
    ["2Z", "CGN", "Changan Airlines", "China"], 
	["3C", "CMV", "Calima Aviacion", "Spain"], 
	["3D", "APG", "Air People International", "Thailand"], 
	["3G", "GBQ", "Gambia Bird", "Gambia"],
	["3H", "AIE", "Air Inuit", "Canada"],
	["3K", "JSA", "Jetstar Asia Airways", "Singapore"], 
	["3L", "ISK", "Intersky", "Austria"],
	["3M", "GFT", "Gulfstream International Airlines", "USA"], 
	["3N", "URG", "Air Urga", "Ukraine"], 
	["3O", "MAC", "Air Arabia Maroc", "Morocco"], 
	["3P", "TNM", "Tiara Air", "Aruba"], 
	["3R", "GAI", "Moskovia Airlines", "Russia"], 
	["3S", "AEN", "Aeroland Airways", "Greece"], 
	["7H", "CAI", "Corendon Airlines", "Turkey"], 
	["7H", "ERH", "ERA Aviation", "USA"], 
	["7I", "CSV", "Coastal Travel Limited", "Tanzania"], 
	["7I", "INC", "Insel Air", "Curacao"], 
	["7J", "TJK", "Tajik Air", "Tajikistan"], 
	["7K", "KGL", "Kolavia/Kogalymavia Airlines", "Russia"], 
	["7L", "CRN", "Aero Caribbean", "Cuba"], 
	["7M", "AAG", "Air Atlantique", "United Kingdom"],
	["PM", "TOS", "Tropic Air", "Belize"], 
	["PN", "CHB", "China West Air", "China"], 
	["PO", "PAC", "Polar Air Cargo", "USA"], 
	["PP", "PJS", "Jet Aviation Business Jets", "Switzerland"], 
	["PQ", "TFK", "Transafrik International", "Sao Tome and Principe"],
	["PR", "PAL", "Philippine Airlines", "Philippines"], 
	["PS", "AUI", "Ukraine International Airlines", "Ukraine"], 
	["PT", "SWN", "West Air Sweden", "Sweden"], 
	["PV", "PNR", "PAN Air Lineas Aereas", "Spain"], 
	["PW", "PRF", "Precision Air Services", "Tanzania"], 
	["PX", "ANG", "Air Niugini", "Papua New Guinea"], 
	["PY", "SLM", "Surinam Airways", "Suriname"], 
	["PZ", "LAP", "TAM Airlines/Transportes Aereos del Mercosur", "Paraguay"], 
	["Q2", "DQA", "Maldivian/Island Aviation Services", "Maldives"], 
	["Q5", "MLA", "40-Mile Air", "USA"], 
	["Q6", "CDP", "Aero Condor", "Peru"], 
	["Q8", "PEC", "Pacific East Asia Cargo Airlines", "Philippines"], 
	["Q8", "TSG", "Trans Air Congo", "Congo"], 
	["QA", "CIM", "Cimber", "Denmark"], 
	["QB", "GFG", "SkyGeorgia", "Georgia"], 
	["QD", "QCL", "Air Class Lineas Aereas", "Uruguay"], 
	["QF", "EAQ", "Eastern Australia Airlines", "Australia"], 
	["QF", "QFA", "Qantas Airways", "Australia"], 
	["QF", "QLK", "QantasLink", "Australia"], 
	["QF", "QNZ", "JetConnect", "New Zealand"], 
	["QF", "SSQ", "Sunstate Airlines", "Australia"], 
	["QH", "LYN", "Kyrgyzstan", "Kyrgyzstan"], 
	["QK", "JZA", "Jazz Aviation/Air Canada Express", "Canada"], 
	["QL", "LER", "LASER Linea Aerea de Servicio Ejecutivo Regional", "Venezuela"], 
	["QL", "RNL", "Aero Lanka/Serendib Express", "Sri Lanka"], 
	["QM", "AML", "Air Malawi", "Malawi"], 
	["QN", "ARR", "Air Armenia", "Armenia"], 
	["QQ", "UTY", "Alliance Airlines", "Australia"], 
	["QR", "QTR", "Qatar Airways", "Qatar"], 
	["QS", "TVS", "Travel Service/Smart Wings", "Czech Rep."], 
	["QT", "TPA", "TAMPA Transportes Aereos Mercantiles Panamericanos", "Colombia"], 
	["QU", "UGX", "East African Airlines", "Uganda"], 
	["QU", "UTN", "UTair-Ukraine", "Ukraine"], 
	["QV", "LAO", "Lao Airlines", "Laos"], 
	["QW", "TCI", "Turks Air Cargo", "Turks and Caicos Islands"],
	["QX", "QXE", "Horizon Air", "USA"], 
	["QY", "BCS", "European Air Transport", "Belgium"], 
	["QZ", "AWQ", "Indonesia AirAsia", "Indonesia"],
	["R0", "RPK", "Royal Airlines", "Pakistan"], 
	["R2", "ORB", "Orenair/Orenburg Airlines", "Russia"], 
	["R3", "SYL", "Yakutia Airlines", "Russia"], 
	["R5", "JAV", "Jordan Aviation", "Jordan"], 
	["R6", "DNU", "DOT LT/Danu Oro Transportas", "Lithuania"], 
	["R7", "OCA", "Aserca Airlines", "Venezuela"], 
	["R9", "CAM", "Camai Air/Village Aviation", "USA"], 
	["RA", "RNA", "Nepal Airlines", "Nepal"], 
	["RB", "SYR", "Syrian Arab Airlines", "Syrian Arab Rep."], 
	["RC", "FLI", "Atlantic Airways", "Faroe Islands"], 
	["RE", "REA", "Stobart Air", "Ireland"], 
	["RF", "FWL", "Florida West International Airways", "USA"], 
	["RH", "RPH", "RPX Airlines/Republic Express Airlines", "Indonesia"], 
	["RJ", "RJA", "Royal Jordanian", "Jordan"], 
	["RK", "RCT", "R Airlines", "Thailand"], 
	["RO", "ROT", "Tarom Romanian Air Transport", "Romania"], 
	["RP", "CHQ", "Chautauqua Airlines", "USA"], 
	["RQ", "KMF", "Kam Air", "Afghanistan"], 
	["RR", "RFR", "Royal Air Force", "United Kingdom"], 
	["RS", "ORF", "Oman Royal Flight", "Oman"], 
	["RS", "SKV", "Sky Regional Airlines/Air Canada Express", "Canada"], 
	["RU", "ABW", "AirBridge Cargo Airlines", "Russia"], 
	["RV", "CPN", "Caspian Airlines Service Company", "Iran"], 
	["RV", "ROU", "Air Canada Rouge", "Canada"], 
	["RW", "RPA", "Republic Airlines", "USA"], 
	["RZ", "LRS", "SANSA Servicios Aereos Nacionales SA", "Costa Rica"],
	["S3", "BBR", "Santa Barbara Airlines", "Venezuela"], 
	["S4", "RZO", "Sata International", "Portugal"], 
	["S5", "TCF", "Shuttle America", "USA"], 
	["S6", "SRR", "Star Air", "Denmark"],
	["S7", "SBI", "S7 Airlines/Siberia Airlines", "Russia"],
	["S8", "SWW", "Shovkoviy Shlyah Airlines", "Ukraine"], 
	["S9", "IKM", "Starbow Airlines", "Ghana"], 
	["SA", "SAA", "South African Airways", "South Africa"], 
	["SB", "ACI", "Aircalin/Air Caledonie International", "New Caledonia"], 
	["SC", "CDG", "Shandong Airlines", "China"], 
	["SD", "SUD", "Sudan Airways", "Sudan"],
	["SE", "XLF", "XL Airways France", "France"], 
	["SF", "DTH", "Tassili Airlines", "Algeria"], 
	["SG", "SEJ", "SpiceJet", "India"], 
	["SI", "AWS", "Arab Wings", "Jordan"], 
	["SI", "BCI", "Blue Islands", "United Kingdom"], 
	["SI", "SPA", "Sierra Pacific Airlines", "USA"], 
	["Z2", "EZD", "Zest Airways", "Philippines"],  
	["Z3", "SMJ", "AV Cargo", "Zimbabwe"],
	["Z6", "UDN", "Dnieproavia", "Ukraine"],  
	["Z8", "AZN", "Linea Aerea Amaszonas", "Bolivia"],  
	["Z8", "MTZ", "Mali Airways", "Mali"],  
	["Z9", "DCP", "Delta Connection Kenya", "Kenya"],  
	["ZA", "SWM", "Sky Wings Asia Airlines", "Cambodia"],  
	["ZB", "MON", "Monarch Airlines", "United Kingdom"],  
	["ZD", "FDN", "Dolphin Air", "United Arab Emirates"],  
	["ZE", "AZE", "Arcus-Air Logistics", "Germany"],  
	["ZE", "ESR", "Eastar Jet", "Korea – Rep. of"],  
	["ZH", "CSZ", "Shenzhen Airlines", "China"],  
	["ZI", "AAF", "Aigle Azur", "France"], 
	["ZJ", "ARC", "Air Routing International", "USA"],
	["ZK", "GLA", "Great Lakes Aviation", "USA"],  
	["ZL", "RXA", "Regional Express", "Australia"],  
	["ZM", "CNB", "CityLine Hungary", "Hungary"],  
	["ZN", "NAY", "NAYSA Navegacion y Servicios Aereos Canarios", "Spain"],  
	["ZP", "AZQ", "Silk Way Airlines", "Azerbaijan"],  
	["ZQ", "LOC", "Locair", "USA"],  
	["ZR", "AZS", "Aviacon Zitotrans", "Russia"],  
	["ZR", "PUN", "Punto Azul", "Equatorial Guinea"],  
	["ZT", "AWC", "Titan Airways", "United Kingdom"],  
	["ZW", "AWI", "Air Wisconsin", "USA"], 
	["ZX", "GGN", "Air Georgian/Air Alliance", "Canada"], 
	["3S", "BOX", "AeroLogic", "Germany"], 
	["3S", "GUY", "Air Guyane Express/Air Antilles Express", "French Guiana"], 
	["3T", "URN", "Turan Air", "Azerbaijan"], 
	["3U", "CSC", "Sichuan Airlines", "China"], 
	["3V", "TAY", "TNT Airways", "Belgium"],
	["3W", "MWI", "Malawian Airlines", "Malawi"],
	["3X", "JAC", "Japan Air Commuter", "Japan"], 
	["3Y", "XBO", "Baseops International", "USA"],
	["3Z", "TVP", "Travel Service Polska", "Poland"], 
	["3Z", "VTS", "Everts Air/Tatonduk Outfitters", "USA"], 
	["3Z", "ZAW", "Zoom Airways", "Bangladesh"], 
	["4A", "AGS", "Air Go Airlines", "Greece"], 
	["4A", "AKL", "Air Kiribati", "Kiribati"],
	["4A", "EYE", "FS Air Service", "USA"], 
	["4B", "PAG", "Perimeter Aviation", "Canada"], 
	["4C", "ARE", "Aires", "Colombia"], 
	["4C", "CGK", "Click Airways", "United Arab Emirates"], 
	["4D", "ASD", "Air Sinai", "Egypt"], 
	["4G", "GZP", "Gazpromavia", "Russia"], 
	["4H", "UBD", "United Airways", "Bangladesh"], 
	["4I", "IZM", "Izair", "Turkey"], 
	["4J", "NWZ", "Nationwide Airlines Zambia", "Zambia"], 
	["4J", "SMR", "Somon Air", "Tajikistan"], 
	["4K", "AAS", "Askari Aviation", "Pakistan"], 
	["4K", "KBA", "Kenn Borek Air", "Canada"], 
	["N5", "SGY", "Skagway Air Service", "USA"], 
	["N8", "MUA", "National Airlines", "USA"], 
	["N9", "NVD", "Avion Express", "Lithuania"], 
	["NA", "NAO", "North American Airlines", "USA"],
	["NC", "NAC", "Northern Air Cargo", "USA"], 
	["NC", "NJS", "Cobham Aviation Services Australia", "Australia"],
	["NE", "NMA", "Nesma Airlines", "Egypt"], 
	["NF", "AVN", "Air Vanuatu", "Vanuatu"], 
	["NH", "ANA", "ANA All-Nippon Airways", "Japan"],
	["NI", "PGA", "Portugalia", "Portugal"], 
	["NJ", "NGB", "Nordic Global Airlines", "Finland"], 
	["NK", "NKS", "Spirit Airlines", "USA"], 
	["NL", "SAI", "Shaheen Air International", "Pakistan"], 
	["NM", "NZM", "Mount Cook Airline", "New Zealand"], 
	["NN", "MOV", "VIM Airlines", "Russia"],
	["NO", "NOS", "Neos", "Italy"], 
	["NP", "NIA", "Nile Air", "Egypt"], 
	["NP", "SKP", "Skytrans Airlines", "Australia"], 
	["NQ", "AJX", "Air Japan", "Japan"], 
	["NS", "HBH", "Hebei Airlines", "China"], 
	["NT", "IBB", "Binter Canarias", "Spain"], 
	["NU", "JTA", "Japan Transocean Air", "Japan"], 
	["NX", "AMU", "Air Macau", "Macau"], 
	["NY", "FNA", "Air Iceland/Flugfelag Islands", "Iceland"], 
	["NZ", "ANZ", "Air New Zealand", "New Zealand"], 
	["NZ", "AWK", "Airwork", "New Zealand"], 
	["NZ", "RLK", "Air Nelson", "New Zealand"], 
	["O2", "JEA", "OLT Jetair", "Poland"], 
	["O4", "ABV", "Antrak Air", "Ghana"], 
	["O9", "NOV", "Nova Airline", "Sudan"], 
	["OA", "OAL", "Olympic Air", "Greece"], 
	["OB", "BOV", "Boliviana de Aviacion", "Bolivia"],
	["OC", "OAV", "Omni Aviacao e Tecnologia/PGA Express", "Portugal"], 
	["OD", "MXD", "Malindo Air", "Malaysia"], 
	["OF", "ENT", "Enter Air", "Poland"], 
	["OF", "TML", "Transports et Travaux Aeriens de Madagascar", "Madagascar"],
	["OJ", "FJM", "Fly Jamaica Airways", "Jamaica"], 
	["OJ", "OLA", "Overland Airways", "Nigeria"], 
	["OK", "CSA", "Czech Airlines", "Czech Rep."], 
	["OM", "MGL", "MIAT Mongolian Airlines", "Mongolia"], 
	["ON", "RON", "Our Airline", "Nauru"],
	["OO", "SKW", "Skywest Airlines", "USA"], 
	["OQ", "CQN", "Chongqing Airlines", "China"], 
	["OR", "CRF", "Krym", "Ukraine"], 
	["OR", "TFL", "Arkefly", "Netherlands"], 
	["OS", "AUA", "Austrian Airlines", "Austria"], 
	["OU", "CTN", "Croatia Airlines", "Croatia"], 
	["OV", "ELL", "Estonian Air", "Estonia"], 
	["OV", "OVA", "Melilla Airlines", "Spain"], 
	["OX", "OEA", "Orient Thai Airlines", "Thailand"], 
	["OY", "ANS", "Andes Lineas Aereas", "Argentina"], 
	["OY", "OAE", "Omni Air Express/Omni Air International", "USA"], 
	["OZ", "AAR", "Asiana Airlines", "Korea – Rep. of"],
	["P0", "PFZ", "Proflight Commuter Services", "Zambia"], 
	["P2", "XAK", "Airkenya Express", "Kenya"],
	["P4", "NSO", "Aerolineas Sosa", "Honduras"], 
	["P5", "RPB", "Copa Airlines Colombia", "Colombia"], 
	["P6", "MUI", "Trans Air", "USA"], 
	["P7", "ESL", "Russian Sky Airlines", "Russia"], 
	["P9", "PVN", "Peruvian Airlines", "Peru"], 
	["PA", "FCL", "Florida Coastal Airlines", "USA"],
	["PB", "SPR", "Provincial Airlines", "Canada"], 
	["PC", "PGT", "Pegasus Airlines", "Turkey"], 
	["PD", "POE", "Porter Airlines", "Canada"], 
	["PE", "PEV", "People’s Viennaline/Altenrhein Luftfahrt", "Austria"], 
	["PF", "PNW", "Palestinian Airlines", "Palestinian Territory"], 
	["PG", "BKP", "Bangkok Airways", "Thailand"], 
	["PH", "PAO", "Polynesian Airlines", "Samoa"], 
	["PJ", "SPM", "Air Saint-Pierre", "St. Pierre and Miquelon"], 
	["PK", "PIA", "Pakistan International Airlines", "Pakistan"],
	["W3", "ARA", "Arik Air", "Nigeria"], 
	["W3", "DNU", "Danu Oro Transportas", "Lithuania"],
	["W3", "SWT", "Swiftair", "Spain"], 
	["W4", "BES", "Aero Services Executive", "France"], 
	["W5", "IRM", "Mahan Air", "Iran"],
	["W6", "WZZ", "Wizz Air", "Hungary"], 
	["W8", "CJT", "CargoJet Airways", "Canada"], 
	["W9", "JAB", "Air Bagan", "Myanmar"],
	["WA", "KLC", "KLM Cityhopper", "Netherlands"], 
	["WB", "RWD", "Rwandair Express", "Rwanda"], 
	["WC", "ISV", "Islena Airlines", "Honduras"],
	["WE", "CWC", "Centurion Air Cargo", "USA"], 
	["WF", "WIF", "Wideroe Flyveselskap", "Norway"], 
	["WG", "SWG", "Sunwing Airlines", "Canada"], 
	["WI", "TDX", "TradeWinds Airlines", "USA"],
	["WJ", "LAL", "Air Labrador", "Canada"], 
	["WK", "EDW", "Edelweiss Air", "Switzerland"], 
	["WM", "WIA", "Winair/Windward Islands Airways", "Sint Maarten"], 
	["WN", "SWA", "Southwest Airlines", "USA"], 
	["WP", "MKU", "Island Air", "USA"], 
	["WR", "WEN", "WestJet Encore", "Canada"], 
	["WS", "WJA", "WestJet", "Canada"], 
	["WT", "WSG", "Wasaya Airways", "Canada"], 
	["WW", "WOW", "WOW air", "Iceland"], 
	["WX", "BCY", "CityJet", "Ireland"], 
	["WY", "OMA", "Oman Air", "Oman"], 
	["WZ", "MDJ", "Jetran Air", "Romania"], 
	["WZ", "VAZ", "Red Wings Airlines", "Russia"], 
	["X3", "TUI", "TUIfly", "Germany"], 
	["X5", "OTJ", "Fly Romania", "Romania"], 
	["X8", "DAP", "Aerovias DAP", "Chile"], 
	["X9", "KHO", "Khors Aircompany", "Ukraine"], 
	["XA", "XAA", "ARINC/Aeronautical Radio Inc.", "USA"],
	["XB", "IAT", "IATA/International Air Transport Association", "Canada"],
	["XC", "KDC", "KD Air", "Canada"], 
	["XF", "VLK", "Vladivostok Air", "Russia"], 
	["XH", "KHH", "Alexandria Airlines", "Egypt"],
	["XH", "XXH", "Special Ground Handling Service", "USA"],
	["XI", "XXI", "AEROTEL/Aeronautical Telecommunications", "Jamaica"],
	["XJ", "TAX", "Thai AirAsia X", "Thailand"], 
	["XK", "CCM", "CCM Airlines/Compagnie Corse Mediterrannee", "France"], 
	["XL", "LNE", "LAN Ecuador", "Ecuador"], 
	["XM", "JLJ", "J-Air", "Japan"], 
	["XM", "JTE", "JetEx/Australian Air Express", "Australia"], 
	["XN", "XAR", "Xpress Air", "Indonesia"], 
	["XQ", "SXS", "SunExpress", "Turkey"], 
	["XR", "OZW", "SkyWest Airlines", "Australia"], 
	["XS", "SIT", "SITA", "Belgium"],
	["XT", "SKT", "Sky Star Airways", "Thailand"], 
	["XU", "AXK", "African Express Airways", "Kenya"], 
	["XY", "KNE", "Nas Air/Al-Khayala Airline", "Saudi Arabia"], 
	["XZ", "EXY", "South African Express Airways", "South Africa"], 
	["Y4", "VOI", "Volaris", "Mexico"], 
	["Y5", "AWA", "Asia Wings", "Kazakhstan"], 
	["Y5", "GMR", "Golden Myanmar Airlines", "Myanmar"], 
	["Y7", "TYA", "Taimyr Air Company", "Russia"], 
	["Y8", "YZR", "Yangtze River Express Airlines", "China"], 
	["Y9", "IRK", "Kish Air", "Iran"], 
	["YC", "LLM", "Yamal Airlines", "Russia"],
	["YF", "CFC", "Canadian Armed Forces", "Canada"], 
	["YG", "OTL", "South Airlines", "Ukraine"], 
	["YI", "RSI", "Air Sunshine", "USA"], 
	["YJ", "NTN", "National Airways", "South Africa"], 
	["YL", "BSA", "Air Bissau International", "Guinea-Bissau"], 
	["YL", "ULG", "U Airlines", "Thailand"],
	["YM", "MGX", "Montenegro Airlines", "Montenegro"], 
	["YN", "CRQ", "Air Creebec", "Canada"], 
	["YO", "MCM", "Heli Air Monaco", "Monaco"],
	["YQ", "POT", "Polet Cargo Airlines", "Russia"], 
	["YR", "EGJ", "Scenic Airlines", "USA"], 
	["YV", "ASH", "Mesa Airlines", "USA"], 
	["YW", "ANE", "Air Nostrum", "Spain"], 
	["MK", "MAU", "Air Mauritius", "Mauritius"], 
	["ML", "BIE", "Air Mediterranee", "France"], 
	["ML", "ETC", "ATTICO African Transport Trading and Investment Co.", "Sudan"], 
	["MM", "APJ", "Peach Aviation", "Japan"], 
	["MM", "MMZ", "euroAtlantic airways", "Portugal"],
	["MN", "CAW", "kulula.com/Comair Commercial Airlines", "South Africa"], 
	["MO", "AUH", "Abu Dhabi Amiri Flight", "United Arab Emirates"], 
	["MO", "CAV", "Calm Air", "Canada"], 
	["MP", "MPH", "Martinair", "Netherlands"], 
	["MQ", "ENY", "Envoy Air/American Eagle", "USA"], 
	["MR", "MML", "Hunnu Air", "Mongolia"], 
	["MS", "MSE", "EgyptAir Express", "Egypt"], 
	["MS", "MSR", "EgyptAir", "Egypt"], 
	["MT", "TCX", "Thomas Cook Airlines", "United Kingdom"], 
	["MU", "CES", "China Eastern Airlines", "China"], 
	["MW", "BUG", "Mokulele Airlines", "USA"], 
	["MW", "MYD", "Maya Island Air", "Belize"], 
	["MY", "MWA", "Midwest Airlines", "Egypt"],
	["MZ", "MNA", "Merpati Nusantara Airlines", "Indonesia"], 
	["N2", "QNK", "Kabo Air", "Nigeria"], 
	["N4", "NWS", "Nordwind Airlines", "Russia"], 
	["N4", "TNB", "Trans Air Benin", "Benin"], 
	["N5", "MDM", "Medavia", "Malta"], 
	["SJ", "CGL", "Seagle Air", "Slovakia"], 
	["SK", "SAS", "SAS Scandinavian Airlines System", "Denmark/Norway/Sweden"], 
	["SL", "TLM", "Thai Lion Air", "Thailand"],
	["SM", "MNP", "Spirit of Manila Airlines", "Philippines"], 
	["SN", "BEL", "Brussels Airlines", "Belgium"], 
	["SO", "HKA", "Superior Aviation", "USA"], 
	["SO", "SLC", "SALSA d’Haiti", "Haiti"], 
	["SP", "SAT", "SATA Air Acores", "Portugal"], 
	["SQ", "SIA", "Singapore Airlines", "Singapore"], 
	["SQ", "SQC", "Singapore Airlines Cargo", "Singapore"], 
	["SS", "CRL", "Corsairfly", "France"], 
	["ST", "GMI", "Germania", "Germany"], 
	["SU", "AFL", "Aeroflot Russian Airlines", "Russia"],
	["SV", "SVA", "Saudi Arabian Airlines", "Saudi Arabia"], 
	["SW", "NMB", "Air Namibia", "Namibia"], 
	["SY", "SCX", "Sun Country Airlines", "USA"], 
	["T0", "TPU", "Taca Peru", "Peru"], 
	["T2", "TMA", "Trans Mediterranean Airways", "Lebanon"], 
	["T3", "EZE", "Eastern Airways", "United Kingdom"], 
	["T5", "TUA", "Turkmenistan Airlines", "Turkmenistan"], 
	["T6", "TVR", "Tavrey Airlines/Tavria Aviakompania", "Ukraine"], 
	["T7", "TJT", "Twin Jet", "France"], 
	["TA", "TAI", "Taca International Airlines", "El Salvador"], 
	["TB", "JAF", "Jetairfly", "Belgium"], 
	["TC", "ATC", "Air Tanzania", "Tanzania"], 
	["TD", "LUR", "Atlantis European Airways", "Armenia"],
	["TF", "SCW", "Malmo Aviation", "Sweden"], 
	["TG", "THA", "Thai Airways International", "Thailand"], 
	["TH", "TSE", "Transmile Air Services", "Malaysia"], 
	["TI", "TOL", "TolAir Services", "Puerto Rico"], 
	["TK", "AJA", "AnadoluJet", "Turkey"], 
	["TK", "THY", "Turkish Airlines", "Turkey"], 
	["TL", "ANO", "Airnorth Regional", "Australia"], 
	["TM", "LAM", "LAM", "Mozambique"], 
	["TN", "THT", "Air Tahiti Nui", "French Polynesia"], 
	["TO", "TVF", "Transavia France", "France"], 
	["TQ", "TDM", "Tandem Aereo", "Moldova"], 
	["TR", "TGW", "Tiger Airways", "Singapore"], 
	["TS", "TSC", "Air Transat", "Canada"],
	["TT", "TGW", "Tiger Airways Australia", "Australia"], 
	["TU", "TAR", "Tunisair", "Tunisia"], 
	["TV", "TBA", "Tibet Airlines", "China"], 
	["TX", "FWI", "Air Caraibes", "Guadeloupe/Martinique"], 
	["TY", "TPC", "Air Caledonie", "New Caledonia"], 
	["TZ", "SCO", "Scoot", "Singapore"], 
	["TZ", "TWG", "Air-taxi europe", "Germany"], 
	["U2", "EZY", "easyJet", "United Kingdom"], 
	["U3", "AIA", "Avies", "Estonia"], 
	["U6", "SVR", "Ural Airlines", "Russia"], 
	["U7", "UGA", "Air Uganda", "Uganda"], 
	["UA", "UAL", "United Airlines", "USA"], 
	["UB", "UBA", "Myanma Airways", "Myanmar"], 
	["UC", "LCO", "LAN Cargo", "Chile"], 
	["UD", "HER", "Hex’Air", "France"],
	["UE", "NAS", "Nasair", "Eritrea"], 
	["UF", "UKM", "UM Air/Ukrainian Mediterranean Airlines", "Ukraine"], 
	["UG", "SEN", "Sevenair", "Tunisia"], 
	["UJ", "GMT", "Magnicharters", "Mexico"], 
	["UJ", "LMU", "AlMasria Universal Airlines", "Egypt"], 
	["UL", "ALK", "SriLankan Airlines", "Sri Lanka"], 
	["UN", "TSO", "Transaero Airlines", "Russia"], 
	["UO", "HKE", "Hong Kong Express", "Hong Kong"], 
	["UP", "BHS", "Bahamasair", "Bahamas"], 
	["UR", "KMV", "UTair Express", "Russia"], 
	["US", "AWE", "US Airways", "USA"], 
	["US", "JIA", "PSA Airlines", "USA"], 
	["US", "PDT", "Piedmont Airlines", "USA"], 
	["UT", "UTA", "UTair Aviation", "Russia"], 
	["UU", "REU", "Air Austral", "Reunion Island"], 
	["UW", "UTP", "Uni-Top Airlines", "China"], 
	["UX", "AEA", "Air Europa", "Spain"], 
	["UZ", "BRQ", "Buraq Air Transport", "Libya"], 
	["V0", "VCV", "Conviasa", "Venezuela"], 
	["V2", "RBY", "Vision Airlines", "USA"], 
	["V3", "KRP", "Carpatair", "Romania"], 
	["V4", "VEC", "Vensecar Internacional", "Venezuela"], 
	["V6", "VOG", "Voyager Airlines", "Bangladesh"], 
	["V7", "VOE", "Volotea", "Spain"], 
	["V8", "TPS", "TAPSA Transportes Aereos Petroleros SA", "Argentina"], 
	["V8", "VAS", "ATRAN Aviatrans Cargo Airlines", "Russia"], 
	["VA", "VAU", "Virgin Australia International Airlines", "Australia"], 
	["VB", "VIV", "Viva Aerobus", "Mexico"], 
	["VC", "VAL", "Voyageur Airways", "Canada"], 
	["VD", "KPA", "Henan Airlines", "China"], 
	["VD", "VJC", "VietJet Air", "Vietnam"], 
	["VF", "VLU", "Valuair", "Singapore"], 
	["VG", "VLM", "VLM", "Belgium"], 
	["VH", "ALV", "Aeropostal Alas de Venezuela", "Venezuela"], 
	["VI", "VDA", "Volga-Dnepr Airlines", "Russia"], 
	["VI", "VES", "Vieques Air Link", "Puerto Rico"], 
	["VL", "VIM", "Air VIA Bulgarian Airways", "Bulgaria"], 
	["VN", "HVN", "Vietnam Airlines", "Vietnam"], 
	["VO", "TYR", "Tyrolean Airways/Austrian Arrows", "Austria"], 
	["VR", "TCV", "TACV Cabo Verde Airlines", "Cape Verde"], 
	["VS", "VIR", "Virgin Atlantic Airways", "United Kingdom"], 
	["VT", "VTA", "Air Tahiti", "French Polynesia"], 
	["VW", "TAO", "Transportes Aeromar", "Mexico"], 
	["VX", "VRD", "Virgin America", "USA"], 
	["VY", "VLG", "Vueling Airlines", "Spain"], 
	["W1", "WDL", "WDL Aviation", "Germany"], 
	["4L", "MJX", "Euroline", "Georgia"], 
	["4M", "DSM", "LAN Argentina", "Argentina"], 
	["4N", "ANT", "Air North Charter", "Canada"], 
	["4O", "AIJ", "Interjet/ABC Aerolineas", "Mexico"], 
	["4P", "SBO", "Stabo Air", "Zambia"], 
	["4Q", "SFW", "Safi Airways", "United Arab Emirates"], 
	["4R", "NTA", "Northern Thunderbird Air", "Canada"], 
	["4T", "BHP", "Belair Airlines", "Switzerland"], 
	["4U", "GWI", "Germanwings", "Germany"], 
	["4W", "AJK", "Allied Air Cargo", "Nigeria"], 
	["4W", "WAV", "Warbelow’s Air Ventures", "USA"], 
	["4X", "MEC", "Air Mercury/Mercury Air Cargo", "USA"], 
	["4Y", "TUD", "Flight Alaska", "USA"], 
	["4Z", "LNK", "Airlink", "South Africa"], 
	["CL", "CLH", "Lufthansa Cityline", "Germany"], 
	["5A", "AIP", "Alpine Air Express", "USA"], 
	["5B", "EAK", "Euro Asia Air International", "Kazakhstan"], 
	["5B", "NCH", "Chanchangi Airlines Nigeria", "Nigeria"], 
	["5C", "ICL", "CAL Cargo Air Lines/Cavei Avir Levitanim", "Israel"], 
	["5C", "NRR", "Nature Air", "Costa Rica"], 
	["5D", "SLI", "Aeromexico Connect", "Mexico"], 
	["5E", "EKA", "Equaflight Service", "Congo"], 
	["5H", "FFV", "Fly540/Five Forty Aviation", "Kenya"], 
	["5J", "CEB", "Cebu Pacific Air", "Philippines"], 
	["5K", "HFY", "Hifly", "Portugal"],
	["EM", "CFS", "Empire Airlines", "USA"], 
	["EN", "DLA", "Air Dolomiti", "Italy"], 
	["EO", "LHN", "Express One International", "USA"],
	["EP", "IRC", "Iran Asseman Airlines", "Iran"],
	["EQ", "TAE", "TAME", "Ecuador"], 
	["ES", "DHX", "SNAS/DHL/DHL International Aviation ME", "Bahrain"], 
	["ET", "ETH", "Ethiopian Airlines", "Ethiopia"], 
	["EU", "UEA", "Chengdu Airlines", "China"], 
	["EV", "ASQ", "ExpressJet Airlines", "USA"], 
	["EW", "EWG", "Eurowings", "Germany"], 
	["EX", "BJK", "Atlantic Airlines", "USA"], 
	["EY", "EFL", "Eagle Air", "Tanzania"], 
	["EY", "ETD", "Etihad Airways", "United Arab Emirates"], 
	["EZ", "EIA", "Evergreen International Airlines", "USA"], 
	["EZ", "SUS", "Sun Air of Scandinavia", "Denmark"], 
	["F3", "FSW", "Faso Airways", "Burkina Faso"], 
	["F3", "FXL", "Fly Excellent", "Sweden"], 
	["F3", "SGB", "Sky King", "USA"],
	["F7", "DWT", "Darwin Airline/Etihad Regional", "Switzerland"],
	["F7", "VRE", "Volare Airlines", "Ukraine"], 
	["F9", "FFT", "Frontier Airlines", "USA"], 
	["FA", "SFR", "Safair/FlySafair", "South Africa"],
	["FB", "LZB", "Bulgaria Air", "Bulgaria"], 
	["FC", "FCX", "Falcon Express Cargo Airlines", "United Arab Emirates"], 
	["FD", "AIQ", "Thai AirAsia", "Thailand"], 
	["FG", "AFG", "Ariana Afghan Airlines", "Afghanistan"], 
	["FI", "ICE", "Icelandair", "Iceland"], 
	["FJ", "FJI", "Fiji Airways", "Fiji"], 
	["IX", "AXB", "Air India Express", "India"], 
	["IY", "IYE", "Yemenia", "Yemen"], 
	["IZ", "AIZ", "Arkia", "Israel"], 
	["J2", "AHC", "AZAL Avia Cargo", "Azerbaijan"], 
	["J2", "AHY", "AZAL Azerbaijan Airlines/AHY", "Azerbaijan"], 
	["J3", "PLR", "Northwestern Air", "Canada"], 
	["J4", "BFL", "Buffalo Airways", "Canada"], 
	["J5", "EPA", "Shenzhen Donghai Airlines", "China"], 
	["J6", "ARW", "Jamaica Air Shuttle", "Jamaica"], 
	["J7", "DNM", "Denim Air", "Netherlands"], 
	["J8", "BVT", "Berjaya Air", "Malaysia"], 
	["J9", "JZR", "Jazeera Airways", "Kuwait"], 
	["JA", "BON", "B & H Airlines", "Bosnia-Herzegovina"], 
	["JA", "JGN", "Jagson Airlines", "India"],
	["JB", "JBA", "Helijet International", "Canada"], 
	["JC", "JEX", "JAL Express", "Japan"], 
	["JE", "MNO", "Mango", "South Africa"], 
	["JF", "LAB", "LAB Flying Service", "USA"], 
	["JH", "FDA", "Fuji Dream Airlines", "Japan"], 
	["JJ", "AGX", "Aviogenex", "Serbia"], 
	["JL", "JAL", "Japan Airlines", "Japan"], 
	["JM", "JKT", "Jetstar Hong Kong", "Italy"], 
	["JN", "NLV", "Livingston Compagnia Aerea", "Italy"], 
	["JP", "ADR", "Adria Airways", "Slovenia"], 
	["JQ", "JST", "Jetstar Airways", "Australia"], 
	["JQ", "LAV", "AlbaStar", "Spain"], 
	["JR", "JOY", "Joy Air", "China"], 
	["JS", "KOR", "Air Koryo", "Korea – Dem. People’s Rep."], 
	["JT", "LNI", "Lion Airlines/Lion Mentari Air", "Indonesia"], 
	["JU", "JAT", "Jat Airways", "Serbia"], 
	["JV", "BLS", "Bearskin Airlines", "Canada"], 
	["JW", "VNL", "Vanilla Air", "Japan"], 
	["JZ", "IWY", "Air Turks and Caicos", "Turks and Caicos Islands"], 
	["K2", "ELO", "EuroLOT", "Poland"],
	["K4", "CKS", "Kalitta Air", "USA"], 
	["K5", "ABE", "Aban Air", "Iran"], 
	["K5", "SQH", "Wings of Alaska/SeaPort Airlines", "USA"], 
	["K6", "KHV", "Cambodia Angkor Air", "Cambodia"], 
	["K8", "ZAK", "Zambia Skyways", "Zambia"], 
	["K9", "ESD", "Esen Air", "Kyrgyzstan"], 
	["K9", "KFS", "Kalitta Charters", "USA"], 
	["K9", "KRI", "Krylo Aviakompania", "Russia"], 
	["KA", "HDA", "Dragonair/Hong Kong Dragon Airlines", "Hong Kong"], 
	["KB", "DRK", "Druk Air", "Bhutan"], 
	["KC", "KZR", "Air Astana", "Kazakhstan"], 
	["KE", "KAL", "Korean Air", "Korea – Rep. of"], 
	["KF", "BLF", "Blue1", "Finland"], 
	["KG", "GTV", "Aerogaviota", "Cuba"], 
	["KH", "AAH", "Aloha Air Cargo", "USA"], 
	["KK", "KKK", "AtlasJet", "Turkey"], 
	["KL", "KLM", "KLM Royal Dutch Airlines", "Netherlands"],
	["KM", "AMC", "Air Malta", "Malta"], 
	["KN", "CUA", "China United Airlines", "China"], 
	["KO", "AER", "Alaska Central Express", "USA"], 
	["KO", "QNK", "Kabo Air", "Nigeria"], 
	["KQ", "KQA", "Kenya Airways", "Kenya"], 
	["KR", "KMZ", "Comores Aviation", "Comoros"],
	["KS", "PEN", "Penair/Peninsula Airways", "USA"], 
	["KU", "KAC", "Kuwait Airways", "Kuwait"],
	["KW", "KFA", "Kelowna Flightcraft Air Charter", "Canada"], 
	["KX", "CAY", "Cayman Airways", "Cayman Islands"], 
	["KZ", "NCA", "Nippon Cargo Airlines", "Japan"], 
	["L2", "LYC", "Lynden Air Cargo", "USA"], 
	["L3", "JOS", "DHL de Guatemala", "Guatemala"],
	["L5", "LTR", "Lufttransport", "Norway"], 
	["L6", "MAI", "Mauritanian Airlines International", "Mauritania"],
	["L6", "VNZ", "TAM Air/Tbilaviamsheni", "Georgia"], 
	["L7", "LHS", "Lugansk Airlines", "Ukraine"], 
	["LA", "LAN", "LAN Airlines", "Chile"], 
	["LB", "LBR", "Air Costa", "India"],
	["LC", "LOG", "Loganair", "United Kingdom"],
	["LD", "AHK", "Air Hong Kong", "Hong Kong"], 
	["LD", "TUY", "Linea Turistica Aerotuy", "Venezuela"], 
	["LG", "LGL", "Luxair", "Luxembourg"], 
	["LH", "GEC", "Lufthansa Cargo", "Germany"], 
	["LI", "LIA", "LIAT", "Antigua and Barbuda"],
	["LJ", "JNA", "Jin Air", "Korea – Rep. of"], 
	["LJ", "SLA", "Sierra National Airlines", "Sierra Leone"], 
	["LL", "BSK", "Miami Air International", "USA"], 
	["LN", "LAA", "Lybian Arab Airlines", "Libya"], 
	["LO", "LOT", "LOT Polish Airlines", "Poland"], 
	["LP", "LPE", "LAN Peru", "Peru"],
	["LQ", "LAQ", "Lebanese Air Transport", "Lebanon"], 
	["LR", "LRC", "Lacsa", "Costa Rica"],
	["LS", "EXS", "Jet2.com", "United Kingdom"], 
	["LT", "LTU", "Air Lituanica", "Lithuania"], 
	["LU", "LXP", "Lan Express", "Chile"], 
	["LW", "NMI", "Pacific Wings/GeorgiaSkies/New Mexico Airlines", "USA"], 
	["LX", "SWR", "Swiss International Air Lines", "Switzerland"],
	["LX", "SWU", "Swiss European Air Lines", "Switzerland"], 
	["LY", "ELY", "El Al", "Israel"], 
	["M0", "MNG", "Aero Mongolia", "Mongolia"], 
	["M2", "MZS", "Mahfooz Aviation", "Gambia"], 
	["M3", "NFA", "Air Norway/North Flying", "Denmark"], 
	["M6", "AJT", "Amerijet International", "USA"], 
	["M7", "MAA", "MasAir", "Mexico"], 
	["M7", "MSL", "Marsland Aviation", "Sudan"], 
	["M9", "MSI", "Motor Sich Aviakompania", "Ukraine"], 
	["MB", "MNB", "MNG Airlines", "Turkey"], 
	["MC", "MSC", "Air Cairo", "Egypt"],
	["MC", "RCH", "Air Mobility Command", "USA"], 
	["MD", "MDG", "Air Madagascar", "Madagascar"], 
	["ME", "MEA", "MEA Middle East Airlines Airliban", "Lebanon"], 
	["MF", "CXA", "Xiamen Airlines", "China"], 
	["MG", "MIX", "Midex Airlines", "United Arab Emirates"], 
	["MH", "MAS", "Malaysia Airlines", "Malaysia"], 
	["MH", "MWG", "MASwings", "Malaysia"], 
	["MI", "SLK", "SilkAir", "Singapore"], 
	["MJ", "MLR", "Mihin Lanka", "Sri Lanka"], 
	["5K", "ODS", "Odessa Airlines", "Ukraine"], 
	["5M", "HFM", "Hi Fly Malta", "Malta"], 
	["5M", "MEG", "Mega Maldives", "Maldives"], 
	["5N", "AUL", "Nordavia", "Russia"], 
	["5O", "FPO", "Europe Airpost", "France"],
	["5Q", "BQB", "BQB Lineas Aereas", "Uruguay"],
	["5R", "KAJ", "Karthago Airlines", "Tunisia"], 
	["5S", "PSV", "Servicios Aereos Profesionales", "Dominican Rep."], 
	["5T", "MPE", "Canadian North", "Canada"], 
	["5U", "CHG", "Challenge Aero", "Ukraine"], 
	["5U", "LDE", "LADE Lineas Aereas del Estado", "Argentina"], 
	["5V", "UKW", "Lviv Airlines/Lvov Airlines", "Ukraine"], 
	["5X", "UPS", "UPS Airlines/United Parcel Service", "USA"], 
	["5Y", "GTI", "Atlas Air", "USA"], 
	["5Y", "IOS", "Isles of Scilly Skybus", "United Kingdom"], 
	["5Z", "BML", "Bismillah Airlines", "Bangladesh"], 
	["6B", "BLX", "TUIfly Nordic", "Sweden"], 
	["6D", "PAS", "Pelita Air Service", "Indonesia"], 
	["6E", "IGO", "IndiGo Airlines", "India"], 
	["6F", "FAO", "Falcon Air Express", "USA"], 
	["6F", "FRJ", "Afrijet Airlines", "Nigeria"], 
	["6G", "RLX", "Go2Sky", "Slovakia"], 
	["6H", "ISR", "Israir", "Israel"], 
	["6I", "IBZ", "International Business Air", "Sweden"], 
	["6I", "MMD", "Alsie Express/MMD", "Denmark"], 
	["6I", "VVA", "Aviast", "Russia"], 
	["6J", "JBW", "Jubba Airways", "Kenya"], 
	["6J", "SNJ", "Skynet Asia Airways", "Japan"], 
	["6L", "AKK", "Aklak Air", "Canada"], 
	["6R", "DRU", "Alrosa Mirny Air Enterprise", "Russia"], 
	["6R", "TNO", "Aerounion/Aerotransporte de Carga Union", "Mexico"], 
	["6T", "LMT", "Almaty Aviation", "Kazakhstan"], 
	["6W", "SOV", "Saravia Saratov Airlines", "Russia"], 
	["6Y", "LTC", "SmartLynx Airlines", "Latvia"], 
	["7C", "COY", "Coyne Airways", "United Kingdom"],
	["7C", "JJA", "Jeju Air", "Korea – Rep. of"], 
	["7E", "AWU", "Sylt Air", "Germany"], 
	["7F", "FAB", "First Air", "Canada"], 
	["7G", "SFJ", "StarFlyer", "Japan"], 
	["7Q", "TLR", "Air Libya", "Libya"],
	["7S", "RYA", "Arctic Transportation Services/Ryan Air Services", "USA"], 
	["7T", "AGV", "Air Glaciers", "Switzerland"], 
	["7T", "RTM", "Aero Express Del Ecuador", "Ecuador"],
	["7T", "TOB", "Tobruk Air Transport and Cargo", "Libya"], 
	["7W", "WRC", "Wind Rose Aviation", "Ukraine"], 
	["7Y", "AGO", "Angola Air Charter", "Angola"], 
	["7Y", "NYL", "Mid Airlines", "Sudan"], 
	["8C", "ATN", "Air Transport International ATI", "USA"], 
	["8D", "EXV", "Expo Aviation", "Sri Lanka"], 
	["8E", "BRG", "Bering Air", "USA"], 
	["8F", "STP", "STP Airways", "Sao Tome and Principe"], 
	["8H", "HFR", "Heli France", "France"], 
	["8L", "LKE", "Lucky Air", "China"], 
	["8L", "RHC", "Redhill Aviation", "United Kingdom"], 
	["8M", "MMA", "Myanmar Airways International", "Myanmar"], 
	["8N", "NKF", "Barents AirLink/Nordkalottflyg", "Sweden"], 
	["8P", "PCO", "Pacific Coastal Airlines", "Canada"], 
	["8Q", "BAJ", "Baker Aviation", "USA"], 
	["8Q", "OHY", "Onur Air", "Turkey"], 
	["8R", "OLS", "Sol Lineas Aereas", "Argentina"], 
	["8U", "AAW", "Afriqiyah Airways", "Libya"], 
	["8V", "ACP", "Astral Aviation", "Kenya"], 
	["8W", "PWF", "Private Wings Flugcharter", "Germany"], 
	["8Y", "CYZ", "China Postal Airlines", "China"], 
	["8Y", "GGE", "EGA Ecuato Guineana de Aviacion", "Equatorial Guinea"], 
	["9A", "EZX", "Eaglexpress", "Malaysia"], 
	["9C", "WDA", "Wimbi Dira Airways", "Congo – Democratic Rep."],
	["9D", "THE", "Toumai Air Tchad", "Chad"], 
	["9E", "FLG", "Endeavor Air", "USA"],
	["9G", "PGP", "Perm Airlines", "Russia"], 
	["9J", "DAN", "Dana Air", "Nigeria"], 
	["9K", "KAP", "Cape Air", "USA"], 
	["9M", "GLR", "Central Mountain Air", "Canada"], 
	["9N", "NSE", "SATENA", "Colombia"], 
	["9R", "VAP", "Phuket Air", "Thailand"], 
	["9S", "CQH", "Spring Airlines", "China"], 
	["9S", "SOO", "Southern Air", "USA"], 
	["9T", "ABS", "Transwest Air", "Canada"],
	["9T", "RUN", "ACT Airlines", "Turkey"], 
	["9U", "MLD", "Air Moldova", "Moldova"], 
	["9V", "AMV", "AMC Airlines", "Egypt"],
	["9V", "ROI", "Avior Airlines", "Venezuela"], 
	["9W", "JAI", "Jet Airways", "India"], 
	["9X", "AXY", "New Axis Airways", "France"], 
	["A2", "CIU", "Cielos Airlines", "Peru"], 
	["A3", "AEE", "Aegean Airlines", "Greece"],
	["A5", "HOP", "Hop!", "France"], 
	["A8", "BGL", "Benin Golf Air", "Benin"], 
	["A9", "TGZ", "Georgian Airways/Air Zena", "Georgia"], 
	["AA", "AAL", "American Airlines", "USA"], 
	["AB", "BER", "Air Berlin", "Germany"],
	["AC", "ACA", "Air Canada", "Canada"], 
	["AE", "MDA", "Mandarin Airlines", "Taiwan"],
	["AG", "ABR", "Air Contractors", "Ireland"], 
	["AH", "DAH", "Air Algerie", "Algeria"], 
	["AI", "AIA", "Airmark Indonesia", "Indonesia"], 
	["AI", "AIC", "Air India", "India"], 
	["AJ", "NIG", "Aero Contractors", "Nigeria"],
	["AK", "AXM", "AirAsia", "Malaysia"], 
	["AL", "TXC", "Transaviaexport Cargo Airline", "Belarus"], 
	["AM", "AMX", "Aeromexico", "Mexico"], 
	["AP", "ADH", "Air One Smart Carrier", "Italy"], 
	["AR", "ARG", "Aerolineas Argentinas", "Argentina"], 
	["AS", "ASA", "Alaska Airlines", "USA"], 
	["AT", "RAM", "Royal Air Maroc", "Morocco"], 
	["AU", "AUT", "Austral Lineas Aereas", "Argentina"], 
	["AV", "AVA", "Avianca", "Colombia"], 
	["AW", "AWN", "Air Niamey", "Niger"], 
	["AW", "SCH", "CHC Airways", "Netherlands"], 
	["AX", "LOF", "Trans States Airlines", "USA"], 
	["AY", "FIN", "Finnair", "Finland"], 
	["AZ", "AZA", "Alitalia", "Italy"], 
	["B2", "BRU", "Belavia", "Belarus"], 
	["B4", "BCF", "BACH Flugbetriebs", "Austria"], 
	["B4", "BKA", "Bankair", "USA"], 
	["B5", "EXZ", "East African Safari Air Express", "Kenya"], 
	["B6", "JBU", "JetBlue Airways {Jet Blue}", "USA"], 
	["B7", "UIA", "UNI Airways Corporation", "Taiwan"], 
	["B8", "ERT", "Eritrean Airlines", "Eritrea"], 
	["B9", "IRB", "Iran Air Tours", "Iran"],
	["BA", "BAT", "British Airways Limited", "United Kingdom"], 
	["BA", "SHT", "British Airways Shuttle", "United Kingdom"], 
	["BB", "SBS", "Seaborne Airlines", "Virgin Islands – USA"], 
	["BC", "SKY", "Skymark Airlines", "Japan"], 
	["BE", "BEE", "flybe", "United Kingdom"], 
	["BE", "FCM", "flybe Nordic/Finnish Commuter Airlines", "Finland"], 
	["BF", "BBD", "Bluebird Cargo", "Iceland"], 
	["BF", "RSR", "Aero-Service", "Congo"], 
	["BG", "BBC", "Biman Bangladesh", "Bangladesh"], 
	["BH", "BHA", "Hawkair", "Canada"], 
	["BI", "RBA", "Royal Brunei Airlines", "Brunei Darussalam"], 
	["BJ", "BRJ", "Borajet", "Turkey"], 
	["BJ", "LBT", "Nouvelair", "Tunisia"], 
	["BK", "OKA", "Okay Airways", "China"], 
	["BL", "PIC", "Jetstar Pacific Airlines", "Vietnam"], 
	["BM", "BMR", "bmi Regional", "United Kingdom"], 
	["BO", "BBW", "BB Airways", "Nepal"],
	["BP", "BOT", "Air Botswana", "Botswana"], 
	["BQ", "BBV", "Bravo Airlines", "Spain"], 
	["BR", "EVA", "EVA Airways Corporation", "Taiwan"], 
	["BS", "BIH", "British International Helicopters", "United Kingdom"], 
	["BT", "BTI", "Air Baltic", "Latvia"], 
	["BV", "BPA", "Blue Panorama Airlines/Blu-Express", "Italy"], 
	["BW", "BWA", "Caribbean Airlines/Air Jamaica", "Trinidad and Tobago"], 
	["BX", "ABL", "Air Busan", "Korea – Rep. of"], 
	["BY", "TOM", "Thomson Airways", "United Kingdom"], 
	["BZ", "BBG", "Bluebird Airways", "Greece"], 
	["BZ", "BDA", "Blue Dart Aviation", "India"], 
	["BZ", "KEE", "Keystone Air Service", "Canada"], 
	["C2", "CEL", "CEIBA Intercontinental", "Equatorial Guinea"], 
	["C4", "IMX", "Zimex Aviation", "Switzerland"], 
	["C5", "UCA", "Commutair", "USA"], 
	["C6", "CJA", "CanJet", "Canada"], 
	["C7", "CIN", "Cinnamon Air", "Sri Lanka"], 
	["CA", "CAO", "Air China Cargo", "China"], 
	["CA", "CCA", "Air China", "China"], 
	["CA", "CCD", "Dalian Airlines", "China"], 
	["CC", "ABD", "Air Atlanta Icelandic", "Iceland"], 
	["CD", "LLR", "Air India Regional", "India"], 
	["CG", "TOK", "Airlines PNG/Airlines of Papua New Guinea", "Papua New Guinea"],
	["CH", "BMJ", "Bemidji Airlines", "USA"], 
	["CI", "CAL", "China Airlines", "Taiwan"], 
	["CJ", "CFE", "BA CityFlyer Express", "United Kingdom"], 
	["CK", "CKK", "China Cargo Airlines", "China"], 
	["CL", "CLW", "LOT Charters", "Poland"], 
	["CM", "CMP", "Copa Airlines", "Panama"],
	["CN", "GDC", "Grand China Air", "China"], 
	["CP", "CPZ", "Compass Airlines", "USA"], 
	["CQ", "EXL", "Sunshine Express Airlines", "Australia"],
	["CT", "CYL", "Alitalia CityLiner", "Italy"], 
	["CU", "CUB", "Cubana de Aviacion", "Cuba"], 
	["CV", "CLX", "Cargolux", "Luxembourg"], 
	["CV", "CVA", "Air Chathams", "New Zealand"], 
	["CW", "MRS", "Air Marshall Islands", "Marshall Islands"], 
	["CX", "CPA", "Cathay Pacific Airways", "Hong Kong"], 
	["CY", "CYP", "Cyprus Airways", "Cyprus"],
	["CZ", "CSN", "China Southern Airlines", "China"], 
	["D0", "DHK", "DHL Air UK/DHL Air Ltd", "United Kingdom"], 
	["D2", "SSF", "Severstal Aircompany", "Russia"], 
	["D3", "DAO", "Daallo Airlines", "Djibouti"], 
	["D4", "LID", "Alidaunia", "Italy"], 
	["D5", "DAE", "DHL Aero Expreso", "Panama"], 
	["D6", "ILN", "Inter Air", "South Africa"], 
	["D7", "XAX", "AirAsia X", "Malaysia"], 
	["D9", "DNV", "Donavia", "Russia"], 
	["DC", "GAO", "Golden Air", "Sweden"], 
	["DD", "NOK", "Nok Air", "Thailand"], 
	["DE", "CFG", "Condor Airlines", "Germany"], 
	["DF", "DER", "Beijing Capital Airlines", "China"], 
	["DG", "SRQ", "South East Asian Airlines", "Philippines"], 
	["DJ", "VOZ", "Virgin Australia Airlines", "Australia"], 
	["DJ", "PBN", "Virgin Samoa", "Samoa"], 
	["DK", "VKG", "Thomas Cook Airlines Scandinavia", "Denmark"], 
	["DL", "DAL", "Delta Air Lines", "USA"],
	["DN", "SGG", "Senegal Airlines", "USA"], 
	["DQ", "CXT", "Coastal Air Transport", "USA"], 
	["DS", "EZS", "easyJet Switzerland", "Switzerland"], 
	["DT", "DTA", "TAAG Angola Airlines", "Angola"], 
	["DU", "NLH", "Norwegian Long Haul", "Norway"], 
	["DV", "VSV", "Scat Air/PLL Scat Aircompany", "Kazakhstan"], 
	["DW", "UCR", "Aero Charter Ukraine", "Ukraine"], 
	["DX", "DTR", "DAT Danish Air Transport", "Denmark"], 
	["DY", "NAX", "Norwegian Air Shuttle", "Norway"], 
	["E5", "RBG", "Air Arabia Egypt", "Egypt"], 
	["E7", "ESF", "Estafeta Carga Aerea", "Mexico"], 
	["E8", "GTA", "City Airways", "Thailand"], 
	["E9", "EVE", "Evelop Airlines", "Spain"], 
	["EB", "PLM", "Pullmantur Air", "Spain"], 
	["EC", "BOS", "OpenSkies", "United Kingdom"], 
	["EC", "TWN", "Avialeasing Aviation Company", "Uzbekistan"], 
	["ED", "ABQ", "Airblue", "Pakistan"], 
	["EF", "ESY", "EasyFly", "Colombia"], 
	["EG", "ENJ", "Enerjet", "Canada"], 
	["EH", "AKX", "ANA Wings", "Japan"],
	["EI", "EIN", "Aer Lingus", "Ireland"], 
	["EJ", "NEA", "New England Airlines", "USA"], 
	["EK", "UAE", "Emirates", "United Arab Emirates"], 
	["EM", "AEB", "Aero Benin", "Benin"], 
	["FK", "WTA", "Africa West Airlines", "Togo"], 
	["FL", "TRS", "Airtran Airways", "USA"], 
	["FM", "CSH", "Shanghai Airlines", "China"], 
	["FN", "FTZ", "Fastjet", "United Kingdom/Tanzania"], 
	["FN", "RGL", "Royal Air Maroc Express/Regional Airlines", "Morocco"], 
	["FO", "ATM", "Airlines of Tasmania", "Australia"], 
	["FO", "FXX", "Felix Airways", "Yemen"],
	["FP", "FPG", "TAG Aviation", "Switzerland"], 
	["FP", "FRE", "Freedom Air/Aviation Services", "Guam"], 
	["FQ", "TCW", "Thomas Cook Airlines Belgium", "Belgium"], 
	["FR", "RYR", "Ryanair", "Ireland"], 
	["FS", "SYA", "Syphax Airlines", "Tunisia"], 
	["FV", "SDM", "Rossiya Russian Airlines", "Russia"], 
	["FW", "FRI", "Ibex Airlines", "Japan"], 
	["FX", "FDX", "FedEx Express/Federal Express", "USA"], 
	["FY", "FFM", "Firefly", "Malaysia"], 
	["FY", "NWR", "Northwest Regional Airlines", "Australia"],
	["FZ", "FDB", "Flydubai", "United Arab Emirates"], 
	["HD", "ADO", "Hokkaido International Airlines/Air Do", "Japan"], 
	["HE", "LGW", "LGW Luftfahrtgesellschaft Walter", "Germany"],
	["HF", "VRE", "Air Côte d’Ivoire", "Cote d’Ivoire"], 
	["HG", "NLY", "Niki", "Austria"], 
	["HJ", "TMN", "Tasman Cargo Airlines", "Australia"], 
	["HK", "FSC", "Four Star Air Cargo", "Virgin Islands – USA"], 
	["HK", "HAY", "Hamburg Airways", "Germany"], 
	["HM", "SEY", "Air Seychelles", "Seychelles"], 
	["HN", "HVY", "HeavyLift Cargo Airlines", "Australia"], 
	["HN", "PTH", "Proteus Helicopteres", "France"], 
	["HO", "DKH", "Juneyao Airlines", "China"], 
	["HR", "HHN", "Hahn Air", "Germany"], 
	["HS", "HSV", "Svenska Direktflyg", "Sweden"], 
	["HT", "IMP", "Hellenic Imperial Airways", "Greece"], 
	["HU", "CHH", "Hainan Airlines", "China"], 
	["HV", "TRA", "transavia.com/Transavia Airlines", "Netherlands"], 
	["HW", "NWL", "North-Wright Airways", "Canada"], 
	["HX", "CRK", "Hong Kong Airlines", "Hong Kong"], 
	["HY", "UZB", "Uzbekistan Airways", "Uzbekistan"], 
	["HZ", "SHU", "Aurora", "Russia"], 
	["I2", "IBS", "Iberia Express", "Spain"],
	["I4", "FWA", "Interstate Airlines", "Netherlands"], 
	["I5", "CMM", "Air Mali", "Mali"], 
	["I6", "SEQ", "Sky Eyes", "Thailand"], 
	["IA", "IAW", "Iraqi Airways", "Iraq"], 
	["IB", "IBE", "Iberia", "Spain"], 
	["ID", "BTK", "Batik Air", "Indonesia"], 
	["IE", "SOL", "Solomon Airlines", "Solomon Islands"], 
	["IG", "ISS", "Meridiana Fly", "Italy"], 
	["IH", "MZA", "Irtysh Air", "Kazakhstan"], 
	["II", "CSQ", "IBC Airways", "USA"], 
	["IM", "MNJ", "Menajet", "Lebanon"],
	["IR", "IRA", "Iran Air", "Iran"], 
	["IS", "ISA", "Island Airlines", "USA"], 
	["IW", "WON", "Wings Abadi Air", "Indonesia"], 
	["FJ", "FJA", "Pacific Sun/Fiji Airlines", "Fiji"],
	["G2", "VXG", "Avirex Gabon", "Gabon"], 
	["G4", "AAY", "Allegiant Air", "USA"], 
	["G4", "GZD", "Grizodubova Air Company", "Russia"], 
	["G5", "HXA", "China Express Airlines", "China"], 
	["G7", "GJS", "GoJet Airlines", "USA"], 
	["G8", "ENK", "Enkor", "Russia"], 
	["G8", "GOW", "GoAir", "India"], 
	["G9", "ABY", "Air Arabia", "United Arab Emirates"],
	["GA", "GIA", "Garuda Indonesia", "Indonesia"], 
	["GB", "ABX", "ABX Air", "USA"], 
	["GC", "GCB", "Lina Congo", "Congo"], 
	["GC", "GNR", "Gambia International Airlines", "Gambia"], 
	["GE", "TNA", "TransAsia Airways", "Taiwan"], 
	["GF", "GFA", "Gulf Air", "Bahrain"], 
	["GH", "GLP", "Globus", "Russia"], 
	["GJ", "CDC", "Zhejiang Loong Airlines", "China"], 
	["GK", "JJP", "JetStar Japan", "Japan"], 
	["GL", "GRL", "Air Greenland", "Denmark"], 
	["GO", "KZU", "ULS Airlines Cargo Transport", "Turkey"], 
	["GP", "GDR", "Gadair European Airlines", "Spain"], 
	["GP", "GES", "Gestair", "Spain"],
	["GQ", "SEH", "Sky Express", "Greece"],
	["GR", "AUR", "Aurigny Air Services", "United Kingdom"], 
	["GS", "GCR", "Tianjin Airlines", "China"], 
	["GX", "JXX", "Primera Air", "Iceland"], 
	["GY", "GBK", "Gabon Airlines", "Gabon"], 
	["GY", "TMG", "Tri-MG Intra Asia Airlines", "Indonesia"], 
	["H2", "SKU", "Sky Airline", "Chile"], 
	["H3", "HRM", "Hermes Airlines", "Greece"], 
	["H4", "HLI", "Heli Securite Helicopter Airlines", "France"], 
	["H5", "RSY", "I-Fly", "Russia"], 
	["H6", "HAG", "Hageland Aviation Services", "USA"], 
	["H7", "EGU", "Eagle Air", "Uganda"], 
	["H9", "HTH", "Helitt Lineas Aereas", "Spain"], 
	["HA", "HAL", "Hawaiian Airlines", "USA"], 
	["HB", "AAQ", "Asia Atlantic Airlines", "Thailand"], 
];

function identifyAirLineInformations(airCode){
	if (airCode != null){
		var icaoAirCode = airCode.substring(0, 3);
		var numAirCode =  airCode.substring(3, 7);
		var nomeLinhaAerea;
		var icaoRotaVoo;
		var paisLinhaAerea;
		
		var contains = false;
		for (var j = 0; j < airLines.length; j++) {
			if (icaoAirCode == airLines[j][1]){
				nomeLinhaAerea = airLines[j][2];
				icaoRotaVoo =  airLines[j][0] + numAirCode;
				paisLinhaAerea = airLines[j][3];
				contains = true;
			}
		}

		if(contains) {
			var retorno = {idVoo: icaoRotaVoo, airline: nomeLinhaAerea, country: paisLinhaAerea};
			return retorno;
		}
	}

	return null;
}